#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1559332650                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/app/id1559332650                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
# presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : ココドコJAPAN                                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : 無料                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : マニアックすぎる！？日本地理クイズゲーム

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : contact@yhiro.com                               
your_link                                 : contact@yhiro.com                    
your_city                                 : Tokyo                               
email_address                             : contact@yhiro.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : JAPAN05658611
github_username                           : Thomas1102-hiro
youtube_username                          : O9T3BJ98gEWkPDAHDsrsFw



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : 日本の区市町村、あなたはどれくらい知っていますか？
    description                           : 有名なあのまち、マイナーなまち。日本各地にある大小さまざまな区市町村を当てていくゲームです。日本のことをあまり知らないあなた、旅好きでいろんなまちに行ったことがあるあなた、日本地理に自信があるあなた、是非挑戦してみてください！
    fontawesome_icon_name                 : question-circle
    
  - title                                 : このまち、ドコ？　〜概要から、まちの名前をを当てよう！〜
    description                           : 「(　？　)市は、佐賀県の最東端に位置する市である。九州陸路交通の要衝であり、佐賀市、唐津市に次いで佐賀県では第3位の人口を擁している。九州の陸上交通網において…」
    fontawesome_icon_name                 : book-open

  - title                                 : この写真、ドコ？　〜風景から、まちの名前をを当てよう！〜
    description                           : 「五稜郭、（？）ハリストス正教会、（？）山からの夜景…」
    fontawesome_icon_name                 : image

  - title                                 : この旗、ドコ？　〜旗から、まちの名前をを当てよう！〜
    description                           : ー
    fontawesome_icon_name                 : flag

  - title                                 : ドコのお隣？　〜隣のまちから、推理しよう！〜
    description                           : 「このまちのお隣は… 白山市、野々市市、河北郡津幡町、内灘町、富山県：小矢部市、南砺市」
    fontawesome_icon_name                 : th-large
  
  - title                                 : この場所と形…ドコ？　〜地図から、推理しよう！〜
    description                           : ー
    fontawesome_icon_name                 : map-marked-alt

  - title                                 : この人、ドコの市長？　〜…知ってるあはたはマニアック！〜
    description                           : 「この人はどこの首長？　　河村たかし」
    fontawesome_icon_name                 : user-alt

  - title                                 : 難易度は初級から上級まで
    description                           : 都道府県庁所在地など全国的に有名なまちは初級に頻出、中級や上級になれば小さなまちやちょっぴりマイナーなまちが続々登場！
    fontawesome_icon_name                 : fire

  - title                                 : 達成を集め、ココドコスコアランキングで上位をめざそう
    description                           : いかに早く、正解を選べるかで、スコアが決まります。全国ランキングで上位をめざそう！また、一定の条件を満たせば達成も獲得できます！
    fontawesome_icon_name                 : trophy

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/background.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown